# -*- coding: utf-8 -*-
"""ppi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XW6_qhbwmcrNIuLFqXu4NLxPXYc6b1e6
"""

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt & npx localtunnel --port 8501 & curl ipv4.icanhazip.com